redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  container_name: my_app
  links:
    - redis
  ports:
    - 3000:3000
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=3000

