redis:
  image: redis
  container_name: cache
  expose:
    - 6379
  ports:
    - 6379:6379
app:
  build: ./
  links:
    - redis
  ports:
    - "3000-3001:3000"
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=3000

